name: 'Latexmk'
description: 'Run `latexmk` to compile one or more TeX files.'
author: reitermarkus
branding:
  icon: 'book'
  color: 'purple'
inputs:
  directory:
    description: 'Directory in which to run `latexmk`.'
    required: false
  args:
    description: 'Arguments passed to `latexmk`.'
    required: false
    default: '-cd'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.directory }}'
    - '${{ inputs.args }}'
