on:
  pull_request:
  push:
  schedule:
    - cron: '* 3 * * 0' # every Sunday at 3 AM

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
      - name: Test Action
        uses: ./
        with:
          args: '-h'
  build-push:
    uses: reitermarkus/.github/.github/workflows/docker-build-push.yml@main
