on: [pull_request, push]

name: CI

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: azohra/shell-linter@v0.3.0
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker pull '${{ github.actor }}/latexmk' || true
          docker build \
            --cache-from '${{ github.actor }}/latexmk' \
            -t '${{ github.actor }}/latexmk' \
            -f Dockerfile \
            .
      - name: Log into Docker Hub
        run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login -u '${{ github.actor }}' --password-stdin
      - name: Push Docker Image
        run: docker push '${{ github.actor }}/latexmk'
